### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by SUM1NG** [SUM1NG/my-project-practice#1]
### 만들고자 하는 기능이 무엇인가요?
Todo App 카테고리 분류

### 해당 기능을 구현하기 위해 할 일이 무엇인가요??
1. [ ] Todo 카테고리 컴포넌트 생성
2. [ ] fetch를 통해 서버와 통신하는 코드 작성
3. [ ] css로 이쁘게 꾸미기

### 예상 작업 시간
3.5hrs
