### ISSUE TITLE
Todo App 기본 기능 구현

### ISSUE THREAD

**Issue by SUM1NG** [SUM1NG/my-project-practice#2]
1. [x] DB에서 Todo List 받아오기
2. [x] 사용자가 Todo List를 작성하고 DB에 전송하기
3. [x] 사용자가 만들었던 Todo List에서 특정 항목을 삭제하기
